import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sundown Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://db.onlinewebfonts.com/c/c00931e8b3cca8082101c210353fe27e?family=NeueHaasDisplay-Mediu"
          rel="stylesheet"
        />
        <link
          href="https://db.onlinewebfonts.com/c/cddfddeff0f66d9f03e9df2585ea819e?family=NeueHaasDisplay-Roman"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
